-- this schema sql will destroy all data in database
BEGIN TRANSACTION;

DROP TABLE IF EXISTS users;
CREATE TABLE users
(
	id VARCHAR PRIMARY KEY,
	name VARCHAR(50) NOT NULL,
	password VARCHAR(50) NOT NULL,
	admin INTEGER,
	created_at INTEGER NOT NULL,
	seq INTEGER
);

--add initial user
INSERT INTO users(id, name, password, admin, created_at)VALUES("9b2116db4162478f81f374a6797c3840", "admin", "d033e22ae348aeb5660fc2140aec35850c4da997", 1, 1437453425);

DROP TABLE IF EXISTS arrays;
CREATE TABLE arrays
(
	id VARCHAR(50) PRIMARY KEY,
	name VARCHAR(50) NOT NULL,
	device VARCHAR(50) NOT NULL,
	level INTEGER NOT NULL,
	capacity BIGINT NOT NULL,
	chunk_size INTEGER NOT NULL,
	created_at INTEGER NOT NULL,
	state INTEGER
);

DROP TABLE IF EXISTS disks;
CREATE TABLE disks
(
	id VARCHAR(50) PRIMARY KEY,
	device VARCHAR(50) NOT NULL,
	name VARCHAR(50) NOT NULL,
	capacity BIGINT NOT NULL,
	state INTEGER,
	array_id VARCHAR(50),
	slot INTEGER
);

DROP TABLE IF EXISTS pvs;
CREATE TABLE pvs
(
	id VARCHAR(50) PRIMARY KEY,
	name VARCHAR(50) NOT NULL,
	uuid VARCHAR(50) NOT NULL,
	vg_name VARCHAR(50),
	state INTEGER
);

DROP TABLE IF EXISTS vgs;
CREATE TABLE vgs
(
	id VARCHAR(50) PRIMARY KEY,
	name VARCHAR(50) NOT NULL,
	state INTEGER,
	size BIGINT
);

DROP TABLE IF EXISTS lvms;
CREATE TABLE lvms
(
	id VARCHAR(50) PRIMARY KEY,
	name VARCHAR(50) NOT NULL,
	path VARCHAR(50) NOT NULL,
	vg_name VARCHAR(50) NOT NULL,
	state INTEGER,
	size BIGINT
);

DROP TABLE IF EXISTS targets;
CREATE TABLE targets
(
	id VARCHAR(50) PRIMARY KEY,
	tid INTEGER NOT NULL,
	name VARCHAR(50) NOT NULL,
	iqn VARCHAR(100) NOT NULL,
	driver VARCHAR(50) NOT NULL,
	state INTEGER
);

DROP TABLE IF EXISTS luns;
CREATE TABLE luns
(
	id VARCHAR(50) PRIMARY KEY,
	lid INTEGER NOT NULL,
	name VARCHAR(50) NOT NULL,
	type VARCHAR(50) NOT NULL,
	size BIGINT,
	tid VARCHAR(50),
	state INTEGER
);

DROP TABLE IF EXISTS events;
CREATE TABLE events
(
	id VARCHAR(50) PRIMARY KEY,
	level INTEGER NOT NULL,
	category INTEGER NOT NULL,
	type INTEGER,
	action INTEGER,
	message TEXT,
	created_at INTEGER NOT NULL
);
COMMIT;
